# Range : 

---

Range = X(lagest) - X (lowest)

In [1]:
import numpy as np
A=np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5], [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])
A

B=A.T
B

a=np.ptp(B, axis=0)
b=np.ptp(B,axis=1)

print("Range in Array A:",a)
print("Range in Array B:",b)

Range in Array A: [12.  10.   8.   6.5]
Range in Array B: [ 7.   6.5  8.   7.5  4.5 11.  11.5]


# Quartile

---



In [ ]:
A=np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5], [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])

B=A.T

a=np.percentile(B,27,axis=0, interpolation='lower')
b=np.percentile(B,25,axis=1, interpolation='lower')
c=np.percentile(B,75,axis=0, interpolation='lower')
d=np.percentile(B,50,axis=0, interpolation='lower')

print(a)

print(b)

print(c)

print(d)

[9.5 9.  7.5 9. ]
[8.  7.5 9.  7.  9.5 7.  7.5]
[14.  15.5 11.  12. ]
[11.  14.5 10.5 11.5]


# inter-qurtile range

---




In [ ]:
import numpy as np
from scipy.stats import iqr
A=np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5], [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])

B=A.T

a=iqr(B, axis=0 , rng=(25, 75), interpolation='lower')
b=iqr(B, axis=1 , rng=(25, 75), interpolation='lower')

print(a,b)

[4.5 6.5 3.5 3. ] [3.5 3.5 2.5 5.  2.5 8.  8. ]


# Variance

---



In [ ]:
import numpy as np
A=np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5],
  [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])

B=A.T

a = np.var(B,axis=0)
b = np.var(B,axis=1)

print(a)

print(b)

[13.98979592 12.8877551   6.12244898  3.92857143]
[ 6.546875  5.921875  8.796875  7.546875  2.875    16.5      19.0625  ]


# Standard deviation

---



In [ ]:
import numpy as np
A=np.array([[10,14,11,7,9.5,15,19],[8,9,17,14.5,12,18,15.5],
  [15,7.5,11.5,10,10.5,7,11],[11.5,11,9,12,14,12,7.5]])
B=A.T
a = np.std(B,axis=0)
b = np.std(B,axis=1)
print(a)

print(b)

[3.74029356 3.58995196 2.4743583  1.98206242]
[2.55868619 2.43349029 2.96595263 2.74715762 1.6955825  4.0620192
 4.3660623 ]
