# Data_preprocessing

###### NUMPY

In [4]:
import numpy as np

In [11]:
arr=np.random.randint(2,125,10)

In [13]:
arr

array([29, 26, 90, 52, 89, 88, 42, 23, 19, 32])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(10,)

In [19]:
arr2=np.array(([3,5,2,7,3],[8,5,85,6,3]))

In [20]:
arr2

array([[ 3,  5,  2,  7,  3],
       [ 8,  5, 85,  6,  3]])

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr2.shape

(2, 5)

In [23]:
arr2[0:2,0:2]

array([[3, 5],
       [8, 5]])

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

In [25]:
a.shape

(16,)

In [27]:
b=a.reshape((4,4))

In [28]:
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [29]:
np.linspace(5,100,25)

array([  5.        ,   8.95833333,  12.91666667,  16.875     ,
        20.83333333,  24.79166667,  28.75      ,  32.70833333,
        36.66666667,  40.625     ,  44.58333333,  48.54166667,
        52.5       ,  56.45833333,  60.41666667,  64.375     ,
        68.33333333,  72.29166667,  76.25      ,  80.20833333,
        84.16666667,  88.125     ,  92.08333333,  96.04166667,
       100.        ])

In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

arr3 = arr3.reshape(4,4)

print(arr3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [33]:
arr4 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160],np.float32)

arr4 = arr4.reshape(4,4)

print(arr4)

[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]]


In [34]:
print(arr3-arr4)

[[  -9.  -18.  -27.  -36.]
 [ -45.  -54.  -63.  -72.]
 [ -81.  -90.  -99. -108.]
 [-117. -126. -135. -144.]]


In [36]:
np.add(arr3,arr4)

array([[ 11.,  22.,  33.,  44.],
       [ 55.,  66.,  77.,  88.],
       [ 99., 110., 121., 132.],
       [143., 154., 165., 176.]], dtype=float32)

In [38]:
np.subtract(arr3,arr4)

array([[  -9.,  -18.,  -27.,  -36.],
       [ -45.,  -54.,  -63.,  -72.],
       [ -81.,  -90.,  -99., -108.],
       [-117., -126., -135., -144.]], dtype=float32)