In [1]:
import numpy as np

In [2]:
my_lt=[3,53,34,5,3,3,4]

In [3]:
arr=np.array(my_lt)

In [4]:
arr

array([ 3, 53, 34,  5,  3,  3,  4])

In [5]:
np.arange(5,99)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [7]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.random.seed(101)
arr2=np.random.randint(5,123,9)

In [29]:
arr2

array([100,  16,  86,  75,  68,  92,  80, 116,  14])