In [2]:
import numpy as np

In [3]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8103, 0.2412, 0.6995],
        [0.9520, 0.8044, 0.6235],
        [0.8022, 0.4941, 0.2160],
        [0.5460, 0.2715, 0.9185],
        [0.4589, 0.1977, 0.5572]])


In [6]:
#GPU availability

In [4]:
import torch
torch.cuda.is_available()

False

In [5]:
# initializing two arrays
a = np.array(2)
b = np.array(1)
print(a,b)   

2 1


In [6]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

3
-1
2
2.0


#Let’s now see how we can do the same using PyTorch on tensors. So, first, let’s initialize two tensors:

In [7]:
# initializing two tensors
a = torch.tensor(2)
b = torch.tensor(1)
print(a,b)

tensor(2) tensor(1)


perform the operations which we saw in NumPy

In [8]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

tensor(3)
tensor(-1)
tensor(2)
tensor(2)


..\aten\src\ATen\native\BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.


##### Matrix Initialization

In [13]:
# matrix of zeros
a = np.zeros((3,3))
print(a)
print(a.shape)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


##### Matrix Initialization with PyTorch

In [14]:
# matrix of zeros
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [ ]:
#random numbers initialization- Numpy

In [15]:
# setting the random seed for numpy
np.random.seed(45)

#matrix of random numbers
a = np.random.randn(3,3)
a

array([[ 0.02637477,  0.2603217 , -0.39514554],
       [-0.20430091, -1.27163265, -2.59687863],
       [ 0.28968091, -0.87330464,  0.39407266]])

In [16]:
# setting the random seed for pytorch
torch.manual_seed(42)

# matrix of random numbers
a = torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

###### matrix operations - numpy

In [17]:
# setting the random seed for numpy and initializing two matrices
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)


# matrix addition
print(np.add(a,b), '\n')

# matrix subtraction
print(np.subtract(a,b), '\n')
 
# matrix multiplication
print(np.dot(a,b), '\n')
 
# matrix multiplication
print(np.divide(a,b))

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]]


In [16]:
###### matrix operations - pytorch

In [18]:
# setting the random seed for pytorch and initializing two tensors
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
# matrix addition
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication
print(torch.mm(a,b), '\n')

# matrix division
print(torch.div(a,b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


Matrix transpose is one technique which is also very useful while creating a neural network from scratch

In [19]:
# original matrix
print(a, '\n') 

# matrix transpose
print(np.transpose(a))

[[ 0.02637477  0.2603217  -0.39514554]
 [-0.20430091 -1.27163265 -2.59687863]
 [ 0.28968091 -0.87330464  0.39407266]] 

[[ 0.02637477 -0.20430091  0.28968091]
 [ 0.2603217  -1.27163265 -0.87330464]
 [-0.39514554 -2.59687863  0.39407266]]


In [20]:
# original matrix
print(a, '\n')

# matrix transpose
torch.t(a)

[[ 0.02637477  0.2603217  -0.39514554]
 [-0.20430091 -1.27163265 -2.59687863]
 [ 0.28968091 -0.87330464  0.39407266]] 



TypeError: t(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

#converting numpy array to tensor

In [21]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


##### AUTOGRAD

In [24]:
# initializing a tensor
a = torch.ones((2,2), requires_grad=True)
a


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [25]:
# performing operations on the tensor
b = a + 5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


b = a + 5

c = mean(b) = Σ(a+5) / 4

the derivative of c w.r.t. a will be ¼ and hence the gradient matrix will be 0.25. Let’s verify this using PyTorch:

In [26]:
# back propagating
c.backward() 

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


##### OPTIM

In [27]:
# importing the optim module
from torch import optim

# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)
 
# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)

#### Neural Network from Scratch


In [28]:
#Input tensor
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

print(X, '\n')
print(y)


tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1.],
        [1.],
        [0.]])


we will define the sigmoid function which will act as the activation function and the derivative of the sigmoid function which will help us in the backpropagation step:

In [29]:
#Sigmoid Function
def sigmoid (x):
   return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function/
def derivatives_sigmoid(x):
   return sigmoid(x) * (1 - sigmoid(x))

initialize the parameters for our model including the number of epochs, learning rate, weights, biases, etc.:

In [30]:
#Variable initialization

epoch=7000 #Setting training iterations

lr=0.1 #Setting learning rate

inputlayer_neurons = X.shape[1] #number of features in data set

hiddenlayer_neurons = 3 #number of hidden layer neurons

output_neurons = 1 #number of neurons in output layer 

In [31]:
#weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)

In [32]:
for i in range(epoch):
   #Forward Propogation
   hidden_layer_input1 = torch.mm(X, wh)
   hidden_layer_input = hidden_layer_input1 + bh
   hidden_layer_activations = sigmoid(hidden_layer_input)
   
   output_layer_input1 = torch.mm(hidden_layer_activations, wout)
   output_layer_input = output_layer_input1 + bout
   output = sigmoid(output_layer_input)

   #Backpropagation
   E = y-output
   slope_output_layer = derivatives_sigmoid(output)
   slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
   d_output = E * slope_output_layer
   Error_at_hidden_layer = torch.mm(d_output, wout.t())
   d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

   wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
   bout += d_output.sum() *lr
   wh += torch.mm(X.t(), d_hiddenlayer) *lr
   bh += d_output.sum() *lr

###### In the forward propagation step, we are calculating the output and finally, in the backward propagation step, we are calculating the error. We will then update the weights and biases using this error.

In [33]:
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[0.9965],
        [0.9963],
        [0.0055]])
