In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_digits  # hand written digit dataset



In [18]:
digits  =  load_digits()

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(digits.data, digits.target, test_size=0.3)

In [32]:
# logistic regression
logi_model  = LogisticRegression()

logi_model.fit(X_train, y_train)

logi_model.score(X_test, y_test)

C:\Users\Digital Suppliers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [33]:
# svm

svm_model  = SVC()

svm_model.fit(X_train, y_train)

svm_model.score(X_test, y_test)

0.975925925925926

In [34]:
# Random Forest

rf_model  = RandomForestClassifier(n_estimators=45)

rf_model.fit(X_train, y_train)

rf_model.score(X_test, y_test)

0.9722222222222222

In [35]:
# k fold cross validation

from sklearn.model_selection import KFold

kfold  =  KFold(n_splits=3)

kfold

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index, test_index in kfold.split([11,12,13,14,15,16,17,18,19]):
    
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [36]:
def model_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [37]:
# Stratified k fold cross validation

from sklearn.model_selection import StratifiedKFold

skfold  =  StratifiedKFold(n_splits=3)

skfold

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [45]:
log_scores  = []
svm_scores  = []
rf_scores   = []

for train_index, test_index in kfold.split(digits.data):
    
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index],digits.target[test_index]
    
    #print(model_score(LogisticRegression(),X_train, X_test, y_train,y_test))
    #print(model_score(SVC(),X_train, X_test, y_train,y_test))
    #print(model_score(RandomForestClassifier(),X_train, X_test, y_train,y_test))
    log_scores.append(model_score(LogisticRegression(),X_train, X_test, y_train,y_test))
    svm_scores.append(model_score(SVC(),X_train, X_test, y_train,y_test))
    rf_scores.append(model_score(RandomForestClassifier(n_estimators=50),X_train, X_test, y_train,y_test))

C:\Users\Digital Suppliers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Digital Suppliers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    htt

In [46]:
log_scores

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [47]:
svm_scores

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [48]:
rf_scores

[0.9265442404006677, 0.9515859766277128, 0.9282136894824707]

In [50]:
# cross validation using built in methods

from sklearn.model_selection import cross_val_score





In [51]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\Digital Suppliers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Digital Suppliers\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    htt

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [52]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [53]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.91388889, 0.95543175, 0.96935933, 0.9275766 ])